### ISSUE TITLE
Native Resolution Images

### ISSUE THREAD

**Issue by MatthewChang** [google-research/batch_rl#13]
Hi,

I've been trying to use the data from rl unplugged in its native resolution (210x160). I hoping to replay the rl unplugged actions from the sequential data release for dopamine into the environment to regenerate the frames. However I think sticky actions is making the behavior not align perfectly. Is the script that was used to generate the data publicly available somewhere? Or is there another way I can use the rl unplugged data in the native resolution? Thanks!

**Comment by agarwl** [comment]
The agents in [`LoggedDQNAgent`](https://github.com/google-research/batch_rl/blob/master/batch_rl/baselines/agents/dqn_agent.py#L29) in this repo [here](https://github.com/google-research/batch_rl/tree/master/batch_rl/baselines) were used to collect the data using the gin config present [here](https://github.com/google-research/batch_rl/blob/master/batch_rl/baselines/configs/dqn.gin). You can just use the `run_experiment.py` script to launch these experiments. It will take about 3-5 days to collect the entire data. Please note that Dopamine does [preprocessing](https://github.com/google/dopamine/blob/master/docs/api_docs/python/dopamine/discrete_domains/atari_lib/AtariPreprocessing.md) of Atari frames to grayscale images and you'd have to write additional code for getting the native resolution images).

Regarding RL Unplugged, If I remember correctly, it used the data from DQN Replay data, so it probably doesn't contain the native resolution images. As an aside, I think prior work on regenerating the frames has probably used the preprocessed frames for regeneration, although I am not sure.
