### ISSUE TITLE
Code for offline continuous control experiments

### ISSUE THREAD

**Issue by CaralHsi** [google-research/batch_rl#16]
Hi, it is very generous for your team to open the code. However, I did not find the code for **Offline Continuous Control Experiments** which shown in Fig. 8 in the paper. Did I miss some part in the batch_rl folder? If not, will you post it someday?

THX.

**Comment by agarwl** [comment]
Hi, the code for the continuous control experiments simply used the code launched the the repo from https://github.com/sfujim/BCQ/tree/master/continuous_BCQ
