### ISSUE TITLE
DQN Trained Model Releases

### ISSUE THREAD

**Issue by idigitopia** [google-research/batch_rl#2]
I was wondering if there are any plans to release pretrained DQN Networks for the Atari Games.

**Comment by theSparta** [comment]
There's no plan as of yet (unfortunately, I didn't store the best checkpoints and stored only the last checkpoints which severly overfit. I would have to retrain the models to store them). What's the use case you were thinking about?

**Comment by idigitopia** [comment]
I was trying to see if the penultimate layer representation of DQN can be used for planning. My initial experiments did not show any positive results so I just wanted to verify that. 

Thank you for the update.
kind regards, 
- Aayam
