### ISSUE TITLE
The flag 'base_dir' is defined twice

### ISSUE THREAD

**Issue by Altriaex** [google-research/batch_rl#20]
MWE:
pip install domaine-rl 
git clone https://github.com/google-research/batch_rl.git
cd batch_rl
python -um batch_rl.tests.atari_init_teste

This test raises:
absl.flags._exceptions.DuplicateFlagError: The flag 'base_dir' is defined twice. First from batch_rl.baselines.train, Second from dopamine.discrete_domains.train.  Description from first occurrence: Base directory to host all required sub-directories. 

And I do find the two definitions.

**Comment by agarwl** [comment]
Yes, I think this broke in one of the recent commits, removing the one from the `batch_rl.baselines.train` should work.

**Comment by maDnemo** [comment]
I found that dopamine.discrete_domains.train is being imported in line 26 of atari_init_test.py. I commented it out and I was able to run the test, though it skipped the last test.

**Comment by agarwl** [comment]
This was fixed in one of the recent commits.
