### ISSUE TITLE
Python version?  

### ISSUE THREAD

**Issue by johmicrot** [google-research/batch_rl#21]
Can we get the python version used in the documentation?  I'm trying to implement this in Ubuntu 20 so I need to manually install a previous version of python.

Would also be helpful to the the versions used for absl-py, atari-py, gin-config, opencv-python, gym, numpy. As well as thewhich virtual environment manager that was used (e.g. conda, venv)

**Comment by agarwl** [comment]
I don't remember which python 3 version was this but python3.6 or python3.7 would probably work -- this code was released in 2019, so I think some of the newer python versions didn't exist back then and python2 wasn't outdated (yet).

Can you possibly send a pull request regarding the specific versions required to run this code -- my guess is that you can use the versions which were available in 2019 (what specifically breaks with the newer versions?)
