### ISSUE TITLE
How to evaluate agents?

### ISSUE THREAD

**Issue by Altriaex** [google-research/batch_rl#23]
I was able to train dqn agents using off-line data. I wonder how to evaluate agents ? e.g. reproduce the figure for Pong in Figure 3?

**Comment by agarwl** [comment]
So, the evaluation is done every iteration in `dopamine` [here](https://github.com/google/dopamine/blob/master/dopamine/discrete_domains/run_experiment.py#L450). Also, if you launched the code in the repository, the evaluation results should be  logged in your tensorboard logs as well as [dopamine logs](https://github.com/google/dopamine/blob/master/dopamine/discrete_domains/run_experiment.py#L490).

**Comment by agarwl** [comment]
@Altriaex was this issue resolved?
