### ISSUE TITLE
No module named 'dopamine.google'

### ISSUE THREAD

**Issue by jzitovsky** [google-research/batch_rl#25]
The `train.py` file located in `batch_rl/fixed_replay` has on line 41 `from dopamine.google import xm_utils`. When I run the `train.py` file (e.g. by running the `fixed_replay_runner_test` test as shown on the README), I get the following error: `ModuleNotFoundError: No module named 'dopamine.google'`. I downloaded the dopamine library as instructed in the README file. I found that replacing this line with what was there from a previous version, `from   dopamine.discrete_domains import train as base_train` allowed the `fixed_replay_runner_test` test to run successfully. Training offline agents also appears to work correctly, in that no errors are thrown and performance appears to improve over iterations according to the saved logs.

Is the `dopamine.google` module from a previous or experimental version of `dopamine-rl`, or have I done something incorrectly? Would changing line 41 to what was there before introduce any issues, such as computational slowdowns or inaccuracies?

**Comment by agarwl** [comment]
This is an internal import and should not be externally imported. Any line xm_utils or dopamine.google should be removed.

**Comment by agarwl** [comment]
#https://github.com/google-research/batch_rl/commit/80bbc006719faca3b002568d37d759ae9f339cd5 resolves this issue. Thanks for bring it to my attention.
