### ISSUE TITLE
a minor modification for download command

### ISSUE THREAD

**Issue by WeiChengTseng** [google-research/batch_rl#26]
Hi,

Thanks for sharing this interesting project. 

In `README.md`, the download command is `gsutil -m cp -R gs://atari-replay-datasets/dqn`. Directly running the command will make us encounter `CommandException: Wrong number of arguments for "cp" command.`. It will work by change the command to `gsutil -m cp -R gs://atari-replay-datasets/dqn ./`. Though it's just a minor modification and naive for the users that are familiar with `gsutil`, it's good for the novice 😄.

**Comment by agarwl** [comment]
Fixed, thanks!
