### ISSUE TITLE
Transform matrix create only once?

### ISSUE THREAD

**Issue by Hyperion-shuo** [google-research/batch_rl#27]
The paper says for each mini-batch randomly draw a categorical distribution. But in the code i  only find the transform_matrix generate once in _create_network function, and is not change during trainning. Maybe i just miss it, the training option uses q_heads, and q_heads read transform_matrix from Network's kwargs, but i can't find where it update.

**Comment by agarwl** [comment]
So, the released code is for tensorflow graph mode, so the transform matrix is a graph op which generates a different random matrix each time it's evaluated in a `sess.run` call. Lemme know if you still have any confusion.

**Comment by Hyperion-shuo** [comment]
I see, the  transform matrix is an option not a constant, thank you so much.
