### ISSUE TITLE
WARNING:absl:Unable to find episode_end_indices. This is expected for old checkpoints.

### ISSUE THREAD

**Issue by MinkyungPark** [google-research/batch_rl#29]
$ gsutil -m cp -R gs://atari-replay-datasets/dqn/Breakout .
I downloaded the atari-replay-datsets with this command, but I don't see episode_end_indices data.

WARNING:absl:Unable to find episode_end_indices. This is expected for old checkpoints.

and I executed the dopamine code and received the following warning. How can I get episode_end_indices data?

I'd really appreciate your help.

**Comment by agarwl** [comment]
Yes, it is expected as this dataset was collected when there was no logic for `episode_end_indices` in Dopamine replay buffer.
