### ISSUE TITLE
About DQN replay dataset

### ISSUE THREAD

**Issue by sglucas** [google-research/batch_rl#32]
Hi

Thank you so much for your contribution. This is a really great repo for students.

I think it will be very nice if we can try the atari offline training with some recently proposed methods.

Could you please recommend some recent  papers about offline rl training on atari? 

Thank you very much!

Best

**Comment by agarwl** [comment]
Here's a biased list:

- Conservative Q-learning
- DR3: Value-Based Deep Reinforcement Learning Requires Explicit Regularization
- Decision Transformer / Multi-game Decision Transformer
- Offline Q-Learning on Diverse Multi-Task Data Both Scales And Generalizes
- Online and Offline Reinforcement Learning by Planning with a Learned Model
- Efficient Offline Policy Optimization with a Learned Model
- Pretraining representations for data-efficient reinforcement learning
