### ISSUE TITLE
Save the trained model to hdf5 file format

### ISSUE THREAD

**Issue by 2bben** [google-research/batch_rl#6]
Hi,

I'm trying to make the trained model made by the offline agents to work with my online environment, which is written in Golang and loads models from hdf5 files. But when I'm looking at the source code from this repo, I can't seem to find a way to do this easily.

Is there an "easy" way to save the trained model as a hdf5 file, not just checkpoints?

**Comment by agarwl** [comment]
I don't understand the question fully but Keras models used in the [repo](https://github.com/google-research/batch_rl/blob/master/batch_rl/multi_head/atari_helpers.py) allow for easy saving to [hdf5 format](https://www.tensorflow.org/guide/keras/save_and_serialize#keras_h5_format). 

Clarification: What is meant by the model which is not different from the network checkpoints?

**Comment by 2bben** [comment]
What I meant by the "model" is the trained weights, but mostly just to differentiate it from checkpoint, since it's already being saved.

If I try to rephrase my problem: I can't seem to find the variable in your code which let me save the model/weights to a hdf5 file, I.e. which variable where I can call `model.save('my_model.h5')` on, so I ca save the model/weights as they do in the web page you linked?

The repo you linked to, didn't quite help. As I can't see where it's being called upon when doing the training from `batch_rl/fixed_replay/train.py` with the dqn agent.

**Comment by agarwl** [comment]
I see, the code heavily builds on top of dopamine and the online and target Q-networks (Keras models) are given by the variables `self.online_convnet` and `self.target_convnet`.  Each agent derives from a base `DQNAgent ` and you can see the models being created [here](https://github.com/google/dopamine/blob/e7d780d7c80954b7c396d984325002d60557f7d1/dopamine/agents/dqn/dqn_agent.py#L243).

You can access these variables, from all the offline agents and simply call save on them -- currently, the saving is done inside the base agent via this [saver](https://github.com/google/dopamine/blob/master/dopamine/agents/dqn/dqn_agent.py#L207) but something like this should work:
```
offline_agent =  OfflineAgent() #create any offline agent (DQN, QR-DQN) from the code
offline_agent.online_convnet.save('my_model.h5')
```

**Comment by agarwl** [comment]
Hi @2bben, were you able to save the trained models?

**Comment by 2bben** [comment]
Hi,

Yes, I was, thanks for the help!

It was still a little bit problematic as the model was not sequential (or at least what the error message told me) and the names on the layers where the same, but that was a quick fix.

**Comment by agarwl** [comment]
If it's not too much trouble, can you please post the snippet you used to save and load the keras model? This might be useful to other people too.

**Comment by 2bben** [comment]
Updated my previous comment
